driver:
  name: docker
platforms:
  - name: localectl_conditional_tests
    image: centos/systemd
    privileged: true
    command: /usr/lib/systemd/systemd --system
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  playbooks:
    converge: playbook.yml
scenario:
  # converge playbook is not idempotent due to test setup and assertions
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
