galaxy_info:
  author: David Roble
  description: Hole punching and local port forwarding for firewalld service
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - firewall
    - firewalld
    - redhat
    - oasis

dependencies: []
