- name: RHSM Subscribe | Using an Activation Key for register to Red Hat CDN
  redhat_subscription:
    state: present
    activationkey: "{{ satellite_rhn_activation_key }}"
    org_id: "{{ satellite_rhn_org }}"
    pool: "{{ satellite_rhn_pool_id }}"
    force_register: true
  when: satellite_rhn_activation_key|length > 0

- name: RHSM Subscribe | Using an Username for register to Red Hat CDN
  redhat_subscription:
    state: present
    username: "{{ satellite_rhn_username }}"
    password: "{{ satellite_rhn_password }}"
    pool: "{{ satellite_rhn_pool_id }}"
    force_register: true
  when: satellite_rhn_username|length > 0
