#Enabling the repos
- name: Enable Repos | Enabling the satellite repos
  command: >-
    /usr/sbin/subscription-manager repos --disable '*'
    --enable rhel-7-server-satellite-{{ satellite_version }}-rpms
    --enable rhel-7-server-rpms
    --enable rhel-server-rhscl-7-rpms
    --enable rhel-7-server-satellite-maintenance-6-rpms
    --enable rhel-7-server-ansible-2.8-rpms
  tags:
    - "rhn"
    - "skip_ansible_lint"  # ANSIBLE0012
