driver:
  name: openstack
platforms:
  - name: passwordless_ssh_openstack
  - name: passwordless_ssh_openstack2
provisioner:
  playbooks:
    verify: ../shared/verify.yml
  inventory:
    group_vars:
      all:
        passwordless_ssh_gather_host_keys: true
        passwordless_ssh_extra_hosts: |-
          {{ groups['all'] | map('extract', hostvars, 'ansible_host') | list }}
verifier:
  name: ansible
