driver:
  name: openstack
platforms:
  - name: nmcli_connections_default
    nics:
      - net-name: provider_net_cci_4
      - net-name: provider_net_cci_9
provisioner:
  inventory:
    group_vars:
      all:
        nmcli_connections:
          - ifname: eth1
verifier:
  name: ansible
