galaxy_info:
  author: Greg Hellings
  description: Install and configure a basic GlusterFS instance with GDeploy
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis
    - gluster

dependencies: []
