- block:
    - name: ensure sshd is installed
      package:
        name: openssh-server
        state: present

    # Opt for lineinfile as this is a file tightly tied to security and we
    # don't want to template in the entire thing and risk breaking something
    # that changes by the packager or distro default files
    - name: disable sshd password auth
      lineinfile:
        dest: "{{ sshd_config_file }}"
        state: present
        regexp: '^PasswordAuthentication'
        line: >-
          PasswordAuthentication
          {{ sshd_allow_password_login | ternary("yes", "no") }}
      when: not sshd_allow_password_login
      notify: restart sshd

    - name: disable root login
      lineinfile:
        dest: "{{ sshd_config_file }}"
        state: present
        regexp: '^PermitRootLogin'
        line: >-
          PermitRootLogin
          {{ sshd_allow_root_login | ternary("yes", "no") }}
      when: not sshd_allow_root_login
      notify: restart sshd
  become: "{{ sshd_become }}"
  become_user: "{{ sshd_become_user }}"
