- name: install gstatus packages
  become: "{{ gluster_gdeploy_become }}"
  become_user: "{{ gluster_gdeploy_become_user }}"
  package:
    name: "{{ gluster_gdeploy_gstatus_packages }}"
    state: present
