driver:
  name: docker
platforms:
  - name: molecule_docker_ci_fedora
    image: fedora:latest
provisioner:
  name: ansible
  playbooks:
    docker:
      create: ../shared/create.yml
      destroy: ../shared/destroy.yml
