- name: register systems
  hosts: all
  vars_files:
    - "{{ lookup('env', 'MOLECULE_SCENARIO_DIRECTORY') }}/../../../../tests/rhsm.yml"
  roles:
    - role: oasis_roles.system.rhsm
      rhsm_repositories:
        enabled:
          - rhel-7-server-rpms
