driver:
  name: openstack
platforms:
  - name: network_bridge_default
provisioner:
  inventory:
    group_vars:
      all:
        network_bridge_devices:
          br0:
            dns:
              - 8.8.8.8
              - 8.8.4.4
            device: eth0
