dependency:
  name: galaxy
  options:
    role-file: molecule/shared/requirements.yml
driver:
  name: openstack
lint:
  name: yamllint
  options:
    # A custom yamllint file for this scenario, details inside the file
    config-file: tests/yamllint.yml
platforms:
  - name: rhsm-release-set-unset
    groups:
      - rhsm
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: ../shared/group_vars
  playbooks:
    cleanup: ../shared/cleanup.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
  config_options:
    defaults:
      stdout_callback: yaml
scenario:
  test_sequence:
    - lint
    - dependency
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # idempotence is explicitly excluded from the test sequence for this
    # scenario, because the playbook is intentionally non-idempotent to
    # allow for inline assertion tasks
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
    junit-xml: junit.xml
  lint:
    name: flake8
