driver:
  name: openstack
platforms:
  - name: docker_default
    image: Fedora-Cloud-Base-32
    flavor: ci.m1.small
provisioner:
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
  inventory:
    group_vars:
      all:
        molecule_openstack_ci_ssh_user: fedora
