galaxy_info:
  author: Greg Hellings
  description: Manage the creation and destruction of container resources
               for running molecule in a container runtime environment
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: Fedora
      versions:
        - all
    - name: CentOS
      versions:
        - all
    - name: RHEL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - oasis
    - molecule

dependencies: []
