galaxy_info:
  author: Andrew Euredjian
  description: Ansible role that manages groups and users
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
