# molecule_openstack_ci_state is intentionally not defaulted
- name: Assert that required state is specified
  assert:
    that:
      - "molecule_openstack_ci_state is defined"
      - "molecule_openstack_ci_state in ('present', 'absent')"
    msg: The "molecule_openstack_ci_state" variable is required,
         and must be set to either "present" or "absent".

- include_tasks: run_hash.yml

- name: Set runtime facts with hashed values
  set_fact:
    hashed_keypair_name: |-
      {{ molecule_openstack_ci_keypair_name }}-{{ run_hash }}

- include_tasks: create.yml
  when: molecule_openstack_ci_state == 'present'

- include_tasks: destroy.yml
  when: molecule_openstack_ci_state == 'absent'
